### ISSUE TITLE
ReferenceError: rc is not defined

### ISSUE THREAD

**Issue by ssuperdreamer** [SeongBrave/gckit#4]
rc is not defined
    at exports.loadFile (/usr/local/lib/node_modules/gckit/packages/lib/utils/load-gckit.js:96:35)
    at CreateFile (/usr/local/lib/node_modules/gckit/packages/lib/helpers/create-file.js:30:23)
    at module.exports.args (/usr/local/lib/node_modules/gckit/packages/lib/helpers/create-file.js:61:10)
    at createViewcontroller._createFile (/usr/local/lib/node_modules/gckit/packages/lib/core-generators/create.js:170:11)
    at createViewcontroller.create (/usr/local/lib/node_modules/gckit/packages/lib/core-generators/create.js:166:16)
    at createViewcontroller.create (/usr/local/lib/node_modules/gckit/packages/lib/core-generators/create-viewcontroller.js:57:11)
    at Create.Generator (/usr/local/lib/node_modules/gckit/packages/lib/core-generators/create.js:198:25)

**Comment by ssuperdreamer** [comment]
安装成功后按照文档执行命令 gckit g product vc 报错

**Comment by ssuperdreamer** [comment]
gckit/packages/lib/utils/load-gckit.js
这个文件96行
  const erc = await fs.pathExists(rc)
rc应该是rFile吧

**Comment by SeongBrave** [comment]
嗯是的，确实这边的问题，近期我会发布一版的，你可以先拷贝一套模板到.gckit目录下即可

**Comment by ssuperdreamer** [comment]
还有个问题，oc语言只生成 .h没生成.m文件 我还在看。。。不懂哪里出问题了

**Comment by ssuperdreamer** [comment]
没有 tempJson/x x x.json 报错，导致只创建.h文件   Issue可以关闭了。。

**Comment by SeongBrave** [comment]
哦哦
