### ISSUE TITLE
gckit g product vc  error

### ISSUE THREAD

**Issue by czjwarrior** [SeongBrave/gckit#8]
/usr/local/lib/node_modules/gckit/packages/shared-utils/lib/env.js:185
      continue
      ^^^^^^^^

SyntaxError: Illegal continue statement: no surrounding iteration statement
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at __dirname.forEach.m (/usr/local/lib/node_modules/gckit/packages/shared-utils/index.js:10:26)

**Comment by Tliens** [comment]
SyntaxError: Illegal continue statement: no surrounding iteration statement
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /usr/local/lib/node_modules/gckit/packages/shared-utils/index.js:10:26
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/local/lib/node_modules/gckit/packages/shared-utils/index.js:9:3)

**Comment by Tliens** [comment]
大哥，还维护吗？我觉还挺好的

**Comment by dongpeng66** [comment]
/usr/local/lib/node_modules/gckit/packages/shared-utils/lib/env.js:185
continue
^^^^^^^^

SyntaxError: Illegal continue statement: no surrounding iteration statement
这个问题咋 解决

**Comment by dongpeng66** [comment]
> /usr/local/lib/node_modules/gckit/packages/shared-utils/lib/env.js

/usr/local/lib/node_modules/gckit/packages/shared-utils/lib/env.js
里面的continue
改成 return true;
